# Generated by Django 3.2.8 on 2022-01-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='annotation',
        ),
        migrations.AlterField(
            model_name='doc',
            name='document',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='doc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Annotated_text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.doc')),
            ],
        ),
    ]
