# Generated by Django 3.2.8 on 2022-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20220119_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Annotated_text',
        ),
    ]
