# Generated by Django 3.2.8 on 2022-01-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20220119_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotated_text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.doc')),
            ],
        ),
    ]
