# Generated by Django 3.2.8 on 2022-01-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_annotated_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='annotations',
            field=models.CharField(default='zrrrrrrrrrrrrazr', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Annotated_text',
        ),
    ]
