# Generated by Django 3.2.8 on 2022-01-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20220119_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='annotations',
            new_name='annotation',
        ),
    ]
